//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demos.Properties
{
    
    internal partial class Resources
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resources.manager == null))
                {
                    Resources.manager = new System.Resources.ResourceManager("Demos.Properties.Resources", typeof(Resources).Assembly);
                }
                return Resources.manager;
            }
        }
        internal static System.Drawing.Bitmap GetBitmap(Resources.BitmapResources id)
        {
            return ((System.Drawing.Bitmap)(ResourceManager.GetObject(((short)(id)))));
        }
        internal static System.Drawing.Font GetFont(Resources.FontResources id)
        {
            return ((System.Drawing.Font)(ResourceManager.GetObject(((short)(id)))));
        }
        [System.SerializableAttribute()]
        internal enum BitmapResources : short
        {
            Qspi = -32580,
            analog = -29953,
            Camera = -29782,
            Wifi2 = -27264,
            Template = -21726,
            battery = -18996,
            start = 28368,
            settingImage = -17023,
            Canfd = -16516,
            Pwm = -9888,
            Piezo = -5876,
            gauge_180 = -43,
            Usb = 1556,
            background = 4557,
            Uart = 11521,
            Sd = 12737,
            Rtc = 14704,
            Generaltest = 16986,
            wifi = 17980,
            Color = 18291,
            gauge_270 = 23705,
            gauge_360 = 25541,
        }
        [System.SerializableAttribute()]
        internal enum FontResources : short
        {
            droid_reg10 = -27850,
            droid_reg12 = -27848,
            droid_reg11 = -27847,
            droid_reg14 = -27846,
            droid_reg09 = -7428,
            droid_reg08 = -7427,
        }
    }
}
