// <auto-generated />
// Generated from CameraContent.tcui — do not edit by hand.

using GHIElectronics.TinyCLR.UI;
using GHIElectronics.TinyCLR.UI.Controls;
using GHIElectronics.TinyCLR.UI.Media;
using Demos.Properties;

namespace Demos {
    public partial class CameraContent {
        private TextFlow _statusText;
        private Button _testButton;

        private void InitializeComponent() {
            this.Width = 480;
            this.Height = 272;
            var _ch1 = new TextFlow();
            this._statusText = _ch1;
            this.Children.Add(_ch1);
            Canvas.SetLeft(_ch1, 5);
            Canvas.SetTop(_ch1, 40);
            var _ch2 = new Button();
            this._testButton = _ch2;
            _ch2.Width = 100;
            _ch2.Height = 30;
            _ch2.HorizontalAlignment = HorizontalAlignment.Left;
            var _child3 = new Text(Resources.GetFont(Resources.FontResources.droid_reg11), "Test");
            _child3.ForeColor = Colors.Black;
            _child3.HorizontalAlignment = HorizontalAlignment.Center;
            _child3.VerticalAlignment = VerticalAlignment.Center;
            _ch2.Child = _child3;
            this.Children.Add(_ch2);
            Canvas.SetLeft(_ch2, 5);
            Canvas.SetTop(_ch2, 227);
        }
    }
}
