// <auto-generated />
// Generated from SystemInfoContent.tcui — do not edit by hand.

using GHIElectronics.TinyCLR.UI;
using GHIElectronics.TinyCLR.UI.Controls;
using GHIElectronics.TinyCLR.UI.Media;
using Demos.Properties;

namespace Demos {
    public partial class SystemInfoContent {
        private Text _deviceText;
        private Text _clockText;
        private Text _ramText;
        private Text _externalRamText;
        private Text _osText;
        private Text _manufacturerText;
        private Text _demoVersionText;

        private void InitializeComponent() {
            this.Width = 480;
            this.Height = 272;
            var _ch1 = new Text(Resources.GetFont(Resources.FontResources.droid_reg12), "Device: SC20260");
            this._deviceText = _ch1;
            _ch1.ForeColor = Colors.White;
            this.Children.Add(_ch1);
            Canvas.SetLeft(_ch1, 20);
            Canvas.SetTop(_ch1, 40);
            var _ch2 = new Text(Resources.GetFont(Resources.FontResources.droid_reg12), "Clock: 480MHz");
            this._clockText = _ch2;
            _ch2.ForeColor = Colors.White;
            this.Children.Add(_ch2);
            Canvas.SetLeft(_ch2, 20);
            Canvas.SetTop(_ch2, 70);
            var _ch3 = new Text(Resources.GetFont(Resources.FontResources.droid_reg12), "Memory: 512KB Total");
            this._ramText = _ch3;
            _ch3.ForeColor = Colors.White;
            this.Children.Add(_ch3);
            Canvas.SetLeft(_ch3, 20);
            Canvas.SetTop(_ch3, 100);
            var _ch4 = new Text(Resources.GetFont(Resources.FontResources.droid_reg12), "External Memory: 32MB Total");
            this._externalRamText = _ch4;
            _ch4.ForeColor = Colors.White;
            this.Children.Add(_ch4);
            Canvas.SetLeft(_ch4, 20);
            Canvas.SetTop(_ch4, 130);
            var _ch5 = new Text(Resources.GetFont(Resources.FontResources.droid_reg12), "OS: TinyCLR OS v3.0.0");
            this._osText = _ch5;
            _ch5.ForeColor = Colors.White;
            this.Children.Add(_ch5);
            Canvas.SetLeft(_ch5, 20);
            Canvas.SetTop(_ch5, 160);
            var _ch6 = new Text(Resources.GetFont(Resources.FontResources.droid_reg12), "Manufacture: GHI Electronics, LLC");
            this._manufacturerText = _ch6;
            _ch6.ForeColor = Colors.White;
            this.Children.Add(_ch6);
            Canvas.SetLeft(_ch6, 20);
            Canvas.SetTop(_ch6, 190);
            var _ch7 = new Text(Resources.GetFont(Resources.FontResources.droid_reg12), "Demo version: 052126");
            this._demoVersionText = _ch7;
            _ch7.ForeColor = Colors.White;
            this.Children.Add(_ch7);
            Canvas.SetLeft(_ch7, 20);
            Canvas.SetTop(_ch7, 220);
        }
    }
}
