// <auto-generated />
// Generated from EndPage.tcui — do not edit by hand.

using GHIElectronics.TinyCLR.UI;
using GHIElectronics.TinyCLR.UI.Controls;
using GHIElectronics.TinyCLR.UI.Media;
using CarWashExample.Properties;

namespace CarWashExample {
    public partial class EndPage {
        private RadioButton _radio1;
        private RadioButton _radio2;
        private RadioButton _radio3;

        private void InitializeComponent() {
            this.Width = 480;
            this.Height = 272;
            this.Background = new LinearGradientBrush(Colors.Blue, Colors.Teal);
            var _ch1 = new Text(Resources.GetFont(Resources.FontResources.NinaB), "Will you:");
            _ch1.ForeColor = Colors.White;
            this.Children.Add(_ch1);
            Canvas.SetLeft(_ch1, 10);
            Canvas.SetTop(_ch1, 10);
            var _ch2 = new CheckBox();
            this.Children.Add(_ch2);
            Canvas.SetLeft(_ch2, 50);
            Canvas.SetTop(_ch2, 50);
            var _ch3 = new Text(Resources.GetFont(Resources.FontResources.NinaB), "Back to us.");
            _ch3.ForeColor = Colors.White;
            this.Children.Add(_ch3);
            Canvas.SetLeft(_ch3, 87);
            Canvas.SetTop(_ch3, 50);
            var _ch4 = new RadioButton();
            this._radio1 = _ch4;
            _ch4.Name = "radio1";
            this.Children.Add(_ch4);
            Canvas.SetLeft(_ch4, 50);
            Canvas.SetTop(_ch4, 100);
            var _ch5 = new Text(Resources.GetFont(Resources.FontResources.NinaB), "Sell your vehicle.");
            _ch5.ForeColor = Colors.White;
            this.Children.Add(_ch5);
            Canvas.SetLeft(_ch5, 87);
            Canvas.SetTop(_ch5, 100);
            var _ch6 = new RadioButton();
            this._radio2 = _ch6;
            _ch6.Name = "radio2";
            this.Children.Add(_ch6);
            Canvas.SetLeft(_ch6, 50);
            Canvas.SetTop(_ch6, 150);
            var _ch7 = new Text(Resources.GetFont(Resources.FontResources.NinaB), "Donate your vehicle.");
            _ch7.ForeColor = Colors.White;
            this.Children.Add(_ch7);
            Canvas.SetLeft(_ch7, 87);
            Canvas.SetTop(_ch7, 150);
            var _ch8 = new RadioButton();
            this._radio3 = _ch8;
            _ch8.Name = "radio3";
            this.Children.Add(_ch8);
            Canvas.SetLeft(_ch8, 50);
            Canvas.SetTop(_ch8, 200);
            var _ch9 = new Text(Resources.GetFont(Resources.FontResources.NinaB), "Not sure yet.");
            _ch9.ForeColor = Colors.White;
            this.Children.Add(_ch9);
            Canvas.SetLeft(_ch9, 87);
            Canvas.SetTop(_ch9, 200);
            var _ch10 = new Button();
            _ch10.Width = 100;
            _ch10.Height = 40;
            _ch10.Click += this.OnDoneClick;
            _ch10.HorizontalAlignment = HorizontalAlignment.Left;
            var _child11 = new Text(Resources.GetFont(Resources.FontResources.NinaB), "Done!");
            _child11.ForeColor = Colors.Black;
            _child11.HorizontalAlignment = HorizontalAlignment.Center;
            _child11.VerticalAlignment = VerticalAlignment.Center;
            _ch10.Child = _child11;
            this.Children.Add(_ch10);
            Canvas.SetLeft(_ch10, 370);
            Canvas.SetTop(_ch10, 220);
        }
    }
}
