// <auto-generated />
// Generated from LoadingPage.tcui — do not edit by hand.

using GHIElectronics.TinyCLR.UI;
using GHIElectronics.TinyCLR.UI.Controls;
using GHIElectronics.TinyCLR.UI.Media;
using CarWashExample.Properties;

namespace CarWashExample {
    public partial class LoadingPage {
        private ProgressBar _progressBar;

        private void InitializeComponent() {
            this.Width = 480;
            this.Height = 272;
            this.Background = new LinearGradientBrush(Colors.Blue, Colors.Teal);
            var _ch1 = new Text(Resources.GetFont(Resources.FontResources.NinaB), "Processing your payment...");
            _ch1.ForeColor = Colors.White;
            _ch1.HorizontalAlignment = HorizontalAlignment.Center;
            _ch1.VerticalAlignment = VerticalAlignment.Center;
            this.Children.Add(_ch1);
            Canvas.SetLeft(_ch1, 140);
            Canvas.SetTop(_ch1, 220);
            var _ch2 = new ProgressBar();
            this._progressBar = _ch2;
            _ch2.MaxValue = 100;
            _ch2.Value = 0;
            _ch2.Width = 200;
            _ch2.Height = 20;
            _ch2.HorizontalAlignment = HorizontalAlignment.Left;
            this.Children.Add(_ch2);
            Canvas.SetLeft(_ch2, 140);
            Canvas.SetTop(_ch2, 240);
        }
    }
}
