// <auto-generated />
// Generated from PaymentWindow.tcui — do not edit by hand.

using GHIElectronics.TinyCLR.UI;
using GHIElectronics.TinyCLR.UI.Controls;
using GHIElectronics.TinyCLR.UI.Media;
using CarWashExample.Properties;

namespace CarWashExample {
    public partial class PaymentWindow {
        private void InitializeComponent() {
            this.Width = 480;
            this.Height = 272;
            this.Background = new LinearGradientBrush(Colors.Blue, Colors.Teal);
            var _ch1 = new Text(Resources.GetFont(Resources.FontResources.NinaB), "Input your credit card number :");
            _ch1.ForeColor = Colors.White;
            this.Children.Add(_ch1);
            Canvas.SetLeft(_ch1, 10);
            Canvas.SetTop(_ch1, 20);
            var _ch2 = new Text(Resources.GetFont(Resources.FontResources.NinaB), "Expire date :");
            _ch2.ForeColor = Colors.White;
            this.Children.Add(_ch2);
            Canvas.SetLeft(_ch2, 132);
            Canvas.SetTop(_ch2, 50);
            var _ch3 = new Text(Resources.GetFont(Resources.FontResources.NinaB), "Pin :");
            _ch3.ForeColor = Colors.White;
            this.Children.Add(_ch3);
            Canvas.SetLeft(_ch3, 187);
            Canvas.SetTop(_ch3, 80);
            var _ch4 = new TextBox();
            _ch4.Font = Resources.GetFont(Resources.FontResources.NinaB);
            _ch4.Text = "#########";
            _ch4.Width = 120;
            _ch4.Height = 25;
            _ch4.HorizontalAlignment = HorizontalAlignment.Left;
            this.Children.Add(_ch4);
            Canvas.SetLeft(_ch4, 250);
            Canvas.SetTop(_ch4, 15);
            var _ch5 = new TextBox();
            _ch5.Font = Resources.GetFont(Resources.FontResources.NinaB);
            _ch5.Text = "01/01/2020";
            _ch5.Width = 120;
            _ch5.Height = 25;
            _ch5.HorizontalAlignment = HorizontalAlignment.Left;
            this.Children.Add(_ch5);
            Canvas.SetLeft(_ch5, 250);
            Canvas.SetTop(_ch5, 45);
            var _ch6 = new TextBox();
            _ch6.Font = Resources.GetFont(Resources.FontResources.NinaB);
            _ch6.Text = "0000";
            _ch6.Width = 120;
            _ch6.Height = 25;
            _ch6.HorizontalAlignment = HorizontalAlignment.Left;
            this.Children.Add(_ch6);
            Canvas.SetLeft(_ch6, 250);
            Canvas.SetTop(_ch6, 75);
            var _ch7 = new Button();
            _ch7.Width = 100;
            _ch7.Height = 40;
            _ch7.Click += this.OnBackClick;
            _ch7.HorizontalAlignment = HorizontalAlignment.Left;
            var _child8 = new Text(Resources.GetFont(Resources.FontResources.NinaB), "Back");
            _child8.ForeColor = Colors.Black;
            _child8.HorizontalAlignment = HorizontalAlignment.Center;
            _child8.VerticalAlignment = VerticalAlignment.Center;
            _ch7.Child = _child8;
            this.Children.Add(_ch7);
            Canvas.SetLeft(_ch7, 10);
            Canvas.SetTop(_ch7, 220);
            var _ch9 = new Button();
            _ch9.Width = 100;
            _ch9.Height = 40;
            _ch9.Click += this.OnGoClick;
            _ch9.HorizontalAlignment = HorizontalAlignment.Left;
            var _child10 = new Text(Resources.GetFont(Resources.FontResources.NinaB), "Next");
            _child10.ForeColor = Colors.Black;
            _child10.HorizontalAlignment = HorizontalAlignment.Center;
            _child10.VerticalAlignment = VerticalAlignment.Center;
            _ch9.Child = _child10;
            this.Children.Add(_ch9);
            Canvas.SetLeft(_ch9, 370);
            Canvas.SetTop(_ch9, 220);
        }
    }
}
